# Generated by Django 3.2.11 on 2022-06-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='id_edital',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
