# Generated by Django 3.2.11 on 2022-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('cpf_estagiario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estagiario', models.CharField(max_length=200)),
                ('rg_estagiario', models.CharField(max_length=11)),
                ('turno_estagiario', models.CharField(max_length=25)),
                ('email_estagiario', models.CharField(max_length=200)),
                ('semestre_estagiario', models.IntegerField()),
                ('nis_pis_estagiario', models.CharField(max_length=12)),
                ('telefone_estagiario', models.CharField(max_length=12)),
                ('nome_responsavel_estagiario', models.CharField(max_length=200)),
                ('data_nascimento_estagiario', models.CharField(max_length=10)),
                ('genero_estagiario', models.CharField(max_length=12)),
                ('raca_estagiario', models.CharField(max_length=10)),
                ('bairro_estagiario', models.CharField(max_length=200)),
                ('numero_estagiario', models.CharField(max_length=15)),
                ('complemento_estagiario', models.CharField(max_length=200)),
                ('matricula_estagiario', models.CharField(max_length=20)),
                ('situacao_estagiario', models.CharField(max_length=200)),
            ],
        ),
    ]
