# Generated by Django 3.2.11 on 2022-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf_estagiario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
