# Generated by Django 3.2.11 on 2022-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_estagiario_cpf_estagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf_estagiario',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
