# Generated by Django 3.2.11 on 2022-05-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_estagiario_cpf_estagiario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estagiario',
        ),
    ]
