# Generated by Django 3.2.11 on 2022-06-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTE',
            fields=[
                ('id_NTE', models.AutoField(primary_key=True, serialize=False)),
                ('nome_direitor_NTE', models.CharField(max_length=100)),
                ('telefone_NTE', models.CharField(max_length=13)),
                ('email_NTE', models.CharField(max_length=100)),
            ],
        ),
    ]
