# Generated by Django 3.2.11 on 2022-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=50)),
            ],
        ),
    ]
