# Generated by Django 3.2.11 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_programa', models.CharField(max_length=100)),
            ],
        ),
    ]
