# Generated by Django 3.2.11 on 2022-06-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_municipio', models.CharField(max_length=200)),
                ('id_nte_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='nte.nte')),
            ],
        ),
    ]
