# Generated by Django 3.2.11 on 2022-05-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
        ('estagiario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='id_supervisor_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagiarios', to='supervisor.supervisor'),
        ),
    ]
