# Generated by Django 3.2.11 on 2022-05-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0002_estagiario_id_supervisor_estagiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='id_supervisor_estagiario',
            new_name='supervisor_estagiario',
        ),
    ]
