# Generated by Django 3.2.11 on 2022-06-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_remove_estagio_id_programa_estagio'),
        ('supervisor', '0003_rename_id_sede_supervisor_supervisor_sede_supervisor'),
        ('sistemaSec_sede', '0001_initial'),
        ('faculdade', '0001_initial'),
        ('estagiario', '0003_rename_id_supervisor_estagiario_estagiario_supervisor_estagiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='estagio_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estagio', to='estagio.estagio'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='faculdade_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculdade', to='faculdade.faculdade'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='sede_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sede', to='sistemaSec_sede.sede'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='supervisor_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagiario', to='supervisor.supervisor'),
        ),
    ]
