# Generated by Django 3.2.11 on 2022-06-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_rename_id_sede_supervisor_supervisor_sede_supervisor'),
        ('estagiario', '0004_auto_20220619_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='supervisor_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='supervisor.supervisor'),
        ),
    ]
