# Generated by Django 3.2.11 on 2022-07-01 23:21

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0005_alter_estagiario_supervisor_estagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf_estagiario',
            field=cpf_field.models.CPFField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
