# Generated by Django 3.2.11 on 2022-06-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipio', '0001_initial'),
        ('nte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nome_sede', models.CharField(max_length=200)),
                ('codigo_inep_sede', models.CharField(max_length=8)),
                ('telefone_sede', models.CharField(max_length=12)),
                ('nome_responsavel_sede', models.CharField(max_length=200)),
                ('bairro_sede', models.CharField(max_length=50)),
                ('email_sede', models.CharField(max_length=200)),
                ('id_municipio_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='municipio.municipio')),
                ('id_nte_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='nte.nte')),
            ],
        ),
    ]
