# Generated by Django 3.2.11 on 2022-05-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_supervisor', models.CharField(max_length=200)),
                ('telefone_supervisor', models.CharField(max_length=12)),
                ('email_supervisor', models.CharField(max_length=200)),
            ],
        ),
    ]
