# Generated by Django 3.2.11 on 2022-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0001_initial'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='id_sede_supervisor',
            field=models.ManyToManyField(to='sistemaSec_sede.Sede'),
        ),
    ]
