# Generated by Django 3.2.11 on 2022-06-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_supervisor_id_sede_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='id_sede_supervisor',
            new_name='sede_supervisor',
        ),
    ]
