# Generated by Django 3.2.11 on 2022-06-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagio',
            name='id_programa_estagio',
        ),
    ]
